### ISSUE TITLE
Redirect from 'site.com/path/to/page#!' to home page 'site.com/' (problem with Yandex and Bing)

### ISSUE THREAD

**Issue by applecat** [EventedMind/iron-router#1185]
Hi!

I have a problem with people, who's came to my meteor site from Yandex and Bing search engines.
Those engines gives users urls like:
http://site.com/path/to/page#! (instead of normal url http://site.com/path/to/page without #! at the end)
When user goes to this url he is redirected to home page http://site.com.

I know this happens because #!page/path must be redirected to /page/path url and that Yandex and Bing must use urls without #! at the end (for example, Yandex know about this problem and promise to fix it). But can I disable this redirect behavoir now somehow?

Thanx.

**Comment by applecat** [comment]
I made fix-package for this problem called [dimus:iron-hash-fix](https://atmospherejs.com/dimus/iron-hash-fix). 
It loads before iron:router and removes #! at the end of url if it exists.

**Comment by copleykj** [comment]
Iron Router adds the #!  to fix a bug in appecache that causes appcache to
cache a version of your site for every unique URL in your site the user
visits. Removing appcache should fix this if you don't want the hashed URLs.

**Comment by ppryde** [comment]
+1 for this being an issue still, I am not using appcache and still have this problem, have been banging my head against a wall for days trying to fix it so many thanks @applecat! Could be implemented as a fix in iron router or a configurable or is it some form of desirable behaviour to prevent something else?
